.\"	$OpenBSD: rm.1,v 1.46 2025/10/14 kn Exp $
.\"	$NetBSD: rm.1,v 1.8 1995/07/25 19:37:30 jtc Exp $
.\"
.\" Copyright (c) 1990, 1993, 1994
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)rm.1	8.5 (Berkeley) 12/5/94
.\"
.Dd $Mdocdate: October 14 2025 $
.Dt RM 1
.Os
.Sh NAME
.Nm rm
.Nd remove directory entries
.Sh SYNOPSIS
.Nm rm
.Op Fl dfiPRrv
.Ar file ...
.Sh DESCRIPTION
The
.Nm
utility removes the directory entry specified by each
.Ar file
operand.
If a file is not writable and the standard input is a terminal,
.Nm
prompts on the standard error output for confirmation, as required by
.St -p1003.1-2024 .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Remove empty directories as well as other types of files (extension).
.It Fl f
Ignore nonexistent files and never prompt.
.It Fl i
Prompt before every removal.
When both
.Fl f
and
.Fl i
are specified, the last one specified takes effect.
.It Fl P
Attempt to overwrite regular files before unlinking them (extension).
On filesystems that overwrite in place
.Pq currently FFS and MS-DOS ,
files are overwritten once with random data and then removed.
On other filesystems, where in-place overwriting is not reliable,
.Nm
skips the overwrite, emits a warning once per invocation, and the command
will exit with a non-zero status to indicate that
.Fl P
was ineffective.
Removal of the directory entries still proceeds unless another error occurs.
Files with multiple links are unlinked but not overwritten.
Only regular files are ever overwritten.
.It Fl R
Recursively remove file hierarchies rooted in the specified operands.
Implies the behavior of
.Fl d .
If
.Fl i
is specified, the user is prompted before each directory is processed.
.It Fl r
Equivalent to
.Fl R .
.It Fl v
Display the name of each file after it is removed (extension).
.El
.Pp
Symbolic links are removed, not the files they reference.
.Pp
It is an error to attempt to remove the root directory or the operands
.Dq \&.
and
.Dq ..
.Sh EXIT STATUS
.Ex -std rm
.Pp
Additionally, if
.Fl P
was specified and was ineffective for any operand due to the filesystem
not overwriting in place, the command exits with a value greater than zero
even if the directory entries were removed.
.Sh EXAMPLES
Recursively remove a hierarchy:
.Pp
.Dl $ rm -rf foobar
.Pp
Remove a file named
.Pa -f :
.Bd -literal -offset indent
$ rm -- -f
$ rm ./-f
.Ed
.Sh SEE ALSO
.Xr rmdir 1 ,
.Xr unlink 2 ,
.Xr fts_open 3 ,
.Xr symlink 7
.Sh STANDARDS
The
.Nm
utility conforms to
.St -p1003.1-2024 .
The options
.Fl d ,
.Fl P ,
and
.Fl v
are extensions to that specification.
.Sh HISTORY
An
.Nm
command appeared in
.At v1 .
.Sh BUGS
Overwriting does not guarantee erasure on filesystems that do not write
in place (e.g., flash, copy-on-write, or log-structured filesystems),
nor against copies retained by snapshots, journals, caches, or wear leveling.
