.\" $OpenBSD: xpmroot.1,v 1.1.1.1 2006/11/26 10:53:57 matthieu Exp $
.\" t
.\" @(#)xpmroot.1	1.01 8/10/93
.TH XPMROOT 1 "August 13, 1993" "1.01" "FVWM Utilities"
.UC
.SH NAME
xpmroot \- Sets the root window of the current X display to an Xpm pixmap
.SH SYNOPSIS
\fBxpmroot\fP \fIfile\fP
.SH DESCRIPTION
\fIxpmroot\fP reads the Xpm file specified in the command line
and displays it in the root window.
.SH AUTHOR
Rob Nation
