.\" $OpenBSD: FvwmSave.1,v 1.1.1.1 2006/11/26 10:53:53 matthieu Exp $
.\" t
.\" @(#)FvwmSave.1	1/28/94
.TH FVWMSAVE 1 "January 28, 1994" "1.20" "FVWM Modules"
.UC
.SH NAME
FvwmSave \- the FVWM desktop-layout saving module
.SH SYNOPSIS
FvwmSave is spawned by fvwm, so no command line invocation will work.
.SH DESCRIPTION
When called, this module attempts to save your current desktop layout into a
file called new.xinitrc. Ideally, this file will look just like .xinitrc, but
in practice you will have to edit it to get a usable configuration, so keep a
backup of your existing .xinitrc.
.PP
Applications must supply certain hints to the X Window System. Emacs, for
example, does not, so FvwmSave cannot obtain any information from it.
.PP
FvwmSave also assumes that certain command line options are globally accepted
by applications, which may not be the case.
.SH COPYRIGHTS
The NoClutter program, and the concept for interfacing this module to the
window manager, are all original work by Robert Nation.
.PP
Copyright 1994, Robert Nation. No guarantees or warranties or anything are
provided or implied in any way whatsoever. Use this program at your own risk.
Permission to use this program for any purpose is given, as long as the
copyright is kept intact.
.SH INITIALIZATION
During initialization, \fINoClutter\fP searches a configuration file that
describes the time-outs and actions to take. The configuration file is the same
one that fvwm reads during its own initialization.
.PP
If the NoClutter executable is linked to another name, for example `ln -s
NoClutter OtherClutter`, then another module called OtherClutter can be
started with a completely different configuration. This is achieved by changing
the keyword NoClutter to OtherClutter so multiple clutter-reduction programs
can be used.
.PP
FvwmSave follows the same configuration pattern.
.SH INVOCATION
NoClutter can be invoked by inserting the line `Module NoClutter` in the
\&.fvwmrc file. This can be placed on a line by itself if NoClutter is to be
spawned during fvwm's initialization, or it can be bound to a menu, mouse
button, or keystroke to invoke it later. Fvwm searches the directory specified
in the ModulePath configuration option to locate NoClutter.
.PP
FvwmSave is launched by fvwm in the same fashion.
.SH CONFIGURATION OPTIONS
NoClutter reads the same .fvwmrc file as fvwm reads when it starts up and looks
for lines similar to "*NoClutter 3600 Iconify". The format of these lines is
"*NoClutter [time] [command]", where command is any fvwm built-in command, and
time is the interval in seconds between when a window loses focus and when the
command is executed. At most three actions can be specified.
.PP
FvwmSave recognises the analogous "*FvwmSave" syntax.
.SH AUTHOR
Robert Nation and Mr. Per Persson
<pp@solace.mh.se> (Omnion on IRC)
